---
accounts: 
  version: 0.0.0
  required: false
  requirements: 
    liberty: 
      min: 2.1.5
    libertygraph: 
      min: 0.0.0
  description: >
    Estabilishes accounts for clustering users and managing access control
  license: 
    name: LGPL
    description: Licensed under the GNU LESSER GENERAL PUBLIC LICENSE.
    url: http://www.gnu.org/copyleft/lesser.html 
  homeable: true
  tables: 
    account_data: |
      
      account_id I4 PRIMARY,
      content_id I4 NOTNULL
      CONSTRAINT '
      , CONSTRAINT `account_content_ref` FOREIGN KEY (`content_id`) REFERENCES `liberty_content` (`content_id`)
      '
      
    theme_theme: |
      
      content_id I4 NOTNULL PRIMARY,
      theme_logo_id I4,
      primary_color C(6) NOTNULL,
      headline_color C(6) NOTNULL,
      text_color C(6) NOTNULL,
      link_color C(6) NOTNULL
      CONSTRAINT '
      , CONSTRAINT `theme_content_ref` FOREIGN KEY (`content_id`) REFERENCES `liberty_content` (`content_id`)
      , CONSTRAINT `theme_logo_attch_ref` FOREIGN KEY (`theme_logo_id`) REFERENCES `liberty_attachments` (`attachment_id`)
      '
      
    legal_legal: |
      
      content_id I4 NOTNULL PRIMARY,
      
      tos XL,
      privacy_policy XL
      CONSTRAINT '
      , CONSTRAINT `legal_content_ref` FOREIGN KEY (`content_id`) REFERENCES `liberty_content` (`content_id`)
      '
      
    profile_profile: |
      
      content_id I4 NOTNULL PRIMARY,
      profile_mayor_id I4,		profile_mayor_cropped_id I4,		profile_mayor_signature_id I4,		profile_cso_signature_id I4,		profile_service_plan_pdf_id I4,
      mayor_name C(128) NOTNULL,
      cso_name C(128) NOTNULL,
      msg_title C(160),
      msg_summary X,
      msg_body XL,
      serviceplan_summary X,
      mayor_image_caption C(160)
      CONSTRAINT '
      , CONSTRAINT `profile_content_ref` FOREIGN KEY (`content_id`) REFERENCES `liberty_content` (`content_id`)
      , CONSTRAINT `profile_mayor_attch_ref` FOREIGN KEY (`profile_mayor_id`) REFERENCES `liberty_attachments` (`attachment_id`)
      , CONSTRAINT `profile_mayor_cropped_attch_ref` FOREIGN KEY (`profile_mayor_cropped_id`) REFERENCES `liberty_attachments` (`attachment_id`)
      , CONSTRAINT `profile_mayor_signature_attch_ref` FOREIGN KEY (`profile_mayor_signature_id`) REFERENCES `liberty_attachments` (`attachment_id`)
      , CONSTRAINT `profile_cso_signature_attch_ref` FOREIGN KEY (`profile_cso_signature_id`) REFERENCES `liberty_attachments` (`attachment_id`)
      , CONSTRAINT `profile_service_plan_pdf_attch_ref` FOREIGN KEY (`profile_service_plan_pdf_id`) REFERENCES `liberty_attachments` (`attachment_id`)
      '
      
    contact_contact: |
      
      content_id I4 NOTNULL PRIMARY,
      
      contact_name C(128) NOTNULL,
      contact_email C(128) NOTNULL,
      contact_phone C(128) NOTNULL,
      office_street_1 C(256) NOTNULL,
      office_street_2 C(256),
      office_state C(2),
      office_zip C(10),
      contact_form_blurb XL,
      contact_thankyou XL
      CONSTRAINT '
      , CONSTRAINT `contact_content_ref` FOREIGN KEY (`content_id`) REFERENCES `liberty_content` (`content_id`)
      '
      
    contact_inquiry: |
      
      content_id I4 NOTNULL,
      
      user_content_id I4,
      inquiry_msg_body XL
      CONSTRAINT '
      , CONSTRAINT `inquiry_content_ref` FOREIGN KEY (`content_id`) REFERENCES `liberty_content` (`content_id`)
      , CONSTRAINT `user_content_id_ref` FOREIGN KEY (`user_content_id`) REFERENCES `users_users` (`content_id`)
      '
      
    press_press: |
      
      content_id I4 NOTNULL PRIMARY,
      
      pressdata XL
      CONSTRAINT '
      , CONSTRAINT `press_content_ref` FOREIGN KEY (`content_id`) REFERENCES `liberty_content` (`content_id`)
      '
      
    dns_dns: |
      
      content_id I4 NOTNULL PRIMARY,
      
      hostname C(128) NOTNULL UNIQUE
      CONSTRAINT '
      , CONSTRAINT `dns_content_ref` FOREIGN KEY (`content_id`) REFERENCES `liberty_content` (`content_id`)
      '
      
    dns_techcontact: |
      
      content_id I4 NOTNULL PRIMARY,
      
      techcontact_name C(128) NOTNULL,
      techcontact_phone C(128) NOTNULL,
      techcontact_email C(128) NOTNULL
      CONSTRAINT '
      , CONSTRAINT `techcontact_content_ref` FOREIGN KEY (`content_id`) REFERENCES `liberty_content` (`content_id`)
      '
      
    subscribe_subscribetxt: |
      
      content_id I4 NOTNULL PRIMARY,
      
      vol_blurb XL,
      org_blurb XL,
      rslt_blurb XL
      CONSTRAINT '
      , CONSTRAINT `subscribetxt_content_ref` FOREIGN KEY (`content_id`) REFERENCES `liberty_content` (`content_id`)
      '
      
  sequences: 
    account_data_id_seq: 
      start: 1
  permissions: 
    p_accounts_admin: 
      description: Can admin the accounts package
      level: admin
    p_accounts_view: 
      description: Can view the accounts package
      level: basic
    p_account_create: 
      description: Can create a account entry
      level: admin
    p_account_view: 
      description: Can view account entries
      level: basic
    p_account_update: 
      description: Can update any account entry
      level: admin
    p_account_expunge: 
      description: Can delete any account entry
      level: admin
    p_account_admin: 
      description: Can admin any account entry
      level: admin
    p_account_list: 
      description: Can view account lists
      level: basic
    p_theme_theme_service_create: 
      description: Can create a theme entry
      level: owner
    p_theme_theme_service_view: 
      description: Can view theme entries
      level: basic
    p_theme_theme_service_update: 
      description: Can update any theme entry
      level: owner
    p_theme_theme_service_expunge: 
      description: Can delete any theme entry
      level: admin
    p_theme_theme_service_admin: 
      description: Can admin any theme entry
      level: admin
    p_legal_tos_section_create: 
      description: Can create a tos section
      level: owner
    p_legal_tos_section_view: 
      description: Can view tos sections
      level: basic
    p_legal_tos_section_update: 
      description: Can update any tos section
      level: owner
    p_legal_tos_section_expunge: 
      description: Can delete any tos section
      level: admin
    p_legal_tos_section_admin: 
      description: Can admin any tos section
      level: admin
    p_legal_privacypolicy_section_create: 
      description: Can create a privacypolicy section
      level: owner
    p_legal_privacypolicy_section_view: 
      description: Can view privacypolicy sections
      level: basic
    p_legal_privacypolicy_section_update: 
      description: Can update any privacypolicy section
      level: owner
    p_legal_privacypolicy_section_expunge: 
      description: Can delete any privacypolicy section
      level: admin
    p_legal_privacypolicy_section_admin: 
      description: Can admin any privacypolicy section
      level: admin
    p_legal_legal_service_create: 
      description: Can create a legal entry
      level: owner
    p_legal_legal_service_view: 
      description: Can view legal entries
      level: basic
    p_legal_legal_service_update: 
      description: Can update any legal entry
      level: owner
    p_legal_legal_service_expunge: 
      description: Can delete any legal entry
      level: admin
    p_legal_legal_service_admin: 
      description: Can admin any legal entry
      level: admin
    p_profile_serviceplan_section_create: 
      description: Can create a serviceplan section
      level: owner
    p_profile_serviceplan_section_view: 
      description: Can view serviceplan sections
      level: basic
    p_profile_serviceplan_section_update: 
      description: Can update any serviceplan section
      level: owner
    p_profile_serviceplan_section_expunge: 
      description: Can delete any serviceplan section
      level: admin
    p_profile_serviceplan_section_admin: 
      description: Can admin any serviceplan section
      level: admin
    p_profile_profile_service_create: 
      description: Can create a profile entry
      level: owner
    p_profile_profile_service_view: 
      description: Can view profile entries
      level: basic
    p_profile_profile_service_update: 
      description: Can update any profile entry
      level: owner
    p_profile_profile_service_expunge: 
      description: Can delete any profile entry
      level: admin
    p_profile_profile_service_admin: 
      description: Can admin any profile entry
      level: admin
    p_contact_contactinfo_section_create: 
      description: Can create a contactinfo section
      level: owner
    p_contact_contactinfo_section_view: 
      description: Can view contactinfo sections
      level: owner
    p_contact_contactinfo_section_update: 
      description: Can update any contactinfo section
      level: owner
    p_contact_contactinfo_section_expunge: 
      description: Can delete any contactinfo section
      level: admin
    p_contact_contactinfo_section_admin: 
      description: Can admin any contactinfo section
      level: admin
    p_contact_contact_section_create: 
      description: Can create a contact section
      level: owner
    p_contact_contact_section_view: 
      description: Can view contact sections
      level: basic
    p_contact_contact_section_update: 
      description: Can update any contact section
      level: owner
    p_contact_contact_section_expunge: 
      description: Can delete any contact section
      level: admin
    p_contact_contact_section_admin: 
      description: Can admin any contact section
      level: admin
    p_contact_contact_service_create: 
      description: Can create a contact entry
      level: owner
    p_contact_contact_service_view: 
      description: Can view contact entries
      level: basic
    p_contact_contact_service_update: 
      description: Can update any contact entry
      level: owner
    p_contact_contact_service_expunge: 
      description: Can delete any contact entry
      level: admin
    p_contact_contact_service_admin: 
      description: Can admin any contact entry
      level: admin
    p_contact_inquiry_service_create: 
      description: Can create a inquiry entry
      level: basic
    p_contact_inquiry_service_view: 
      description: Can view inquiry entries
      level: admin
    p_contact_inquiry_service_update: 
      description: Can update any inquiry entry
      level: admin
    p_contact_inquiry_service_expunge: 
      description: Can delete any inquiry entry
      level: admin
    p_contact_inquiry_service_admin: 
      description: Can admin any inquiry entry
      level: admin
    p_press_press_section_create: 
      description: Can create a press section
      level: owner
    p_press_press_section_view: 
      description: Can view press sections
      level: basic
    p_press_press_section_update: 
      description: Can update any press section
      level: owner
    p_press_press_section_expunge: 
      description: Can delete any press section
      level: admin
    p_press_press_section_admin: 
      description: Can admin any press section
      level: admin
    p_press_press_service_create: 
      description: Can create a press entry
      level: owner
    p_press_press_service_view: 
      description: Can view press entries
      level: basic
    p_press_press_service_update: 
      description: Can update any press entry
      level: owner
    p_press_press_service_expunge: 
      description: Can delete any press entry
      level: admin
    p_press_press_service_admin: 
      description: Can admin any press entry
      level: admin
    p_dns_technicalcontact_section_create: 
      description: Can create a technicalcontact section
      level: owner
    p_dns_technicalcontact_section_view: 
      description: Can view technicalcontact sections
      level: owner
    p_dns_technicalcontact_section_update: 
      description: Can update any technicalcontact section
      level: owner
    p_dns_technicalcontact_section_expunge: 
      description: Can delete any technicalcontact section
      level: admin
    p_dns_technicalcontact_section_admin: 
      description: Can admin any technicalcontact section
      level: admin
    p_dns_dns_service_create: 
      description: Can create a dns entry
      level: admin
    p_dns_dns_service_view: 
      description: Can view dns entries
      level: basic
    p_dns_dns_service_update: 
      description: Can update any dns entry
      level: admin
    p_dns_dns_service_expunge: 
      description: Can delete any dns entry
      level: admin
    p_dns_dns_service_admin: 
      description: Can admin any dns entry
      level: admin
    p_dns_techcontact_service_create: 
      description: Can create a techcontact entry
      level: admin
    p_dns_techcontact_service_view: 
      description: Can view techcontact entries
      level: basic
    p_dns_techcontact_service_update: 
      description: Can update any techcontact entry
      level: admin
    p_dns_techcontact_service_expunge: 
      description: Can delete any techcontact entry
      level: admin
    p_dns_techcontact_service_admin: 
      description: Can admin any techcontact entry
      level: admin
    p_subscribe_subscribetxt_service_create: 
      description: Can create a subscribetxt entry
      level: owner
    p_subscribe_subscribetxt_service_view: 
      description: Can view subscribetxt entries
      level: basic
    p_subscribe_subscribetxt_service_update: 
      description: Can update any subscribetxt entry
      level: owner
    p_subscribe_subscribetxt_service_expunge: 
      description: Can delete any subscribetxt entry
      level: admin
    p_subscribe_subscribetxt_service_admin: 
      description: Can admin any subscribetxt entry
      level: admin
  preferences: 
    account_default_ordering: account_id_desc
    account_list_title: 'y'
    accounts_account_home_id: 0
    accounts_home_type: account
  contenttypes:
    BitAccount: BitAccount.php
