---
accounts: 
  version: 0.0.0
  required: false
  requirements: 
    liberty:
      min: 2.1.5
    libertygraph:
      min: 0.0.0
 
  description: Estabilishes accounts for clustering users and managing access control
  license: 
    name: LGPL
    description: Licensed under the GNU LESSER GENERAL PUBLIC LICENSE. 
    url: http://www.gnu.org/copyleft/lesser.html
  homeable: true
  pluggable: 1 
  tables: 
    account_data: |
        account_id I4 PRIMARY,
        content_id I4 NOTNULL
        CONSTRAINT '
        , CONSTRAINT `account_content_ref` FOREIGN KEY (`content_id`) REFERENCES `liberty_content` (`content_id`)
        '
    project_data: |
        project_id I4 PRIMARY,
        content_id I4 NOTNULL,
        is_default I1 NOTNULL,
        account_content_id I4 NOTNULL
        CONSTRAINT '
        , CONSTRAINT `project_content_ref` FOREIGN KEY (`content_id`) REFERENCES `liberty_content` (`content_id`)
        , CONSTRAINT `project_account_content_id_ref` FOREIGN KEY (`account_content_id`) REFERENCES `account_data` (`content_id`)
        '
    subproject_data: |
        subproject_id I4 PRIMARY,
        content_id I4 NOTNULL,
        account_content_id I4 NOTNULL,
        project_content_id I4 NOTNULL,
        is_default I1 NOTNULL
        CONSTRAINT '
        , CONSTRAINT `subproject_content_ref` FOREIGN KEY (`content_id`) REFERENCES `liberty_content` (`content_id`)
        , CONSTRAINT `subproject_account_content_id_ref` FOREIGN KEY (`account_content_id`) REFERENCES `account_data` (`content_id`)
        , CONSTRAINT `subproject_project_content_id_ref` FOREIGN KEY (`project_content_id`) REFERENCES `project_data` (`content_id`)
        '
    account_security_data: |
        content_id I4 NOTNULL,
        group_id I4 PRIMARY,
        user_id I4 PRIMARY
        CONSTRAINT '
        , CONSTRAINT `account_security_content_ref` FOREIGN KEY (`content_id`) REFERENCES `subproject_data` (`content_id`)
        , CONSTRAINT `account_security_group_id_ref` FOREIGN KEY (`group_id`) REFERENCES `users_groups` (`group_id`)
        , CONSTRAINT `account_security_user_id_ref` FOREIGN KEY (`user_id`) REFERENCES `users_users` (`user_id`)
        '

    subproject_content_data: |
        content_id I4 NOTNULL,
        subproject_content_id I4 NOTNULL
        CONSTRAINT '
        , CONSTRAINT `subproject_content_content_ref` FOREIGN KEY (`content_id`) REFERENCES `liberty_content` (`content_id`)
        , CONSTRAINT `subproject_content_subproject_content_id_ref` FOREIGN KEY (`subproject_content_id`) REFERENCES `subproject_data` (`content_id`)
        '

  constraints: 
  indexes: 
  sequences: 
    account_data_id_seq: {start: 1}
    project_data_id_seq: {start: 1}
    subproject_data_id_seq: {start: 1}
  preferences: 
    account_default_ordering: account_id_desc
    account_list_title: 'y'
    accounts_account_home_id: 0
    accounts_home_type: account
    project_default_ordering: project_id_desc
    project_list_title: 'y'
    accounts_project_home_id: 0
    subproject_default_ordering: subproject_id_desc
    subproject_list_title: 'y'
    accounts_subproject_home_id: 0
  defaults: 
  permissions: 
    p_accounts_admin:
      description: Can admin the accounts package
      level: admin
    p_accounts_view:
      description: Can view the accounts package
      level: basic
    p_account_create:
      description:  Can create a account entry
      level: admin
    p_account_view:
      description:  Can view account entries
      level: basic
    p_account_update:
      description: Can update any account entry
      level: admin
    p_account_expunge:
      description: Can delete any account entry
      level: admin
    p_account_admin:
      description: Can admin any account entry
      level: admin
    p_project_create:
      description:  Can create a project entry
      level: admin
    p_project_view:
      description:  Can view project entries
      level: basic
    p_project_update:
      description: Can update any project entry
      level: admin
    p_project_expunge:
      description: Can delete any project entry
      level: admin
    p_project_admin:
      description: Can admin any project entry
      level: admin
    p_subproject_create:
      description:  Can create a subproject entry
      level: admin
    p_subproject_view:
      description:  Can view subproject entries
      level: basic
    p_subproject_update:
      description: Can update any subproject entry
      level: admin
    p_subproject_expunge:
      description: Can delete any subproject entry
      level: admin
    p_subproject_admin:
      description: Can admin any subproject entry
      level: admin
    p_account_security_create:
      description:  Can create a account_security entry
      level: registered
    p_account_security_view:
      description:  Can view account_security entries
      level: basic
    p_account_security_update:
      description: Can update any account_security entry
      level: editors
    p_account_security_expunge:
      description: Can delete any account_security entry
      level: admin
    p_account_security_admin:
      description: Can admin any account_security entry
      level: admin
    p_subproject_content_create:
      description:  Can create a subproject_content entry
      level: registered
    p_subproject_content_view:
      description:  Can view subproject_content entries
      level: basic
    p_subproject_content_update:
      description: Can update any subproject_content entry
      level: editors
    p_subproject_content_expunge:
      description: Can delete any subproject_content entry
      level: admin
    p_subproject_content_admin:
      description: Can admin any subproject_content entry
      level: admin
  contenttypes:
    BitAccount: BitAccount.php
    BitProject: BitProject.php
    BitSubProject: BitSubProject.php
  plugins:
    account_security:
      handler_file: AccountSecurity.php
      api_handlers:
        sql:
          content_list_sql: account_security_content_list_sql
        function:
          content_user_perms: account_security_content_user_perms
    subproject_content:
      handler_file: SubProjectContent.php
      api_handlers:
        function:
          content_edit: subproject_content_content_edit
          content_store: subproject_content_content_store
          content_expunge: subproject_content_content_expunge
          content_display: subproject_content_content_display
          content_preview: subproject_content_content_preview
        tpl:
          content_edit_mini: "bitpackage:accounts/subproject_content_content_edit_mini_inc.tpl"
